FROM node:20.18.1-alpine

ARG TELEGRAM_BOT_TOKEN
ARG TELEGRAM_BOT_USERNAME
ARG TELEGRAM_WEBHOOK_SECRET
ARG LLM_BACKEND
ARG OPENAI_API_KEY
ARG OPENAI_MODEL
ARG ANTHROPIC_API_KEY
ARG CLAUDE_MODEL
ARG GEMINI_API_KEY
ARG GEMINI_MODEL
ARG LUMO_API_KEY
ARG LLM_SYSTEM_PROMPT
ARG REDIS_PASSWORD
ARG EXTERNAL_URL
ARG DATABASE_URL
ARG GITHUB_TOKEN
ARG GOOGLE_MAPS_API_KEY
ARG CAPROVER_GIT_COMMIT_SHA

ENV TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ENV TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
ENV TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET}
ENV LLM_BACKEND=${LLM_BACKEND}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV OPENAI_MODEL=${OPENAI_MODEL}
ENV ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
ENV CLAUDE_MODEL=${CLAUDE_MODEL}
ENV GEMINI_API_KEY=${GEMINI_API_KEY}
ENV GEMINI_MODEL=${GEMINI_MODEL}
ENV LUMO_API_KEY=${LUMO_API_KEY}
ENV LLM_SYSTEM_PROMPT=${LLM_SYSTEM_PROMPT}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV EXTERNAL_URL=${EXTERNAL_URL}
ENV DATABASE_URL=${DATABASE_URL}
ENV GITHUB_TOKEN=${GITHUB_TOKEN}
ENV GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
ENV NODE_ENV=production
ENV PORT=80
ENV TZ=Asia/Taipei

RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime && \
    echo "Asia/Taipei" > /etc/timezone && \
    apk del tzdata

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN chmod +x scripts/start.sh

EXPOSE 80

CMD ["./scripts/start.sh"]
