FROM node:20.18.1-alpine

ARG TELEGRAM_BOT_TOKEN
ARG TELEGRAM_BOT_USERNAME
ARG LLM_BACKEND
ARG OPENAI_API_KEY
ARG OPENAI_MODEL
ARG ANTHROPIC_API_KEY
ARG CLAUDE_MODEL
ARG GEMINI_API_KEY
ARG GEMINI_MODEL
ARG LLM_SYSTEM_PROMPT
ARG EXTERNAL_URL

ENV TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ENV TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
ENV LLM_BACKEND=${LLM_BACKEND}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV OPENAI_MODEL=${OPENAI_MODEL}
ENV ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
ENV CLAUDE_MODEL=${CLAUDE_MODEL}
ENV GEMINI_API_KEY=${GEMINI_API_KEY}
ENV GEMINI_MODEL=${GEMINI_MODEL}
ENV LLM_SYSTEM_PROMPT=${LLM_SYSTEM_PROMPT}
ENV EXTERNAL_URL=${EXTERNAL_URL}
ENV NODE_ENV=production
ENV PORT=80

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install 

COPY . .

EXPOSE 80

CMD ["yarn", "start"]
